---
author: "Qiran Chen"
title: "p8105_hw3_qc2336"
output: html_document
date: "2023-10-10"
---

```{r}
library(tidyverse)
library(ggplot2)
```

## Problem 1


```{r}
library(p8105.datasets)
data("instacart")
data("brfss_smart2010")
```

```{r}
tail(instacart,5)
summary(instacart)
instacart|> 
  count(user_id)
```
>> This data has 1384617 observeations. Including 15 variables order id, user id,product d, aisle id departmen id, aisle, department order number, days since prior order, order time, product name and if it is reordered. There are 131209 unique user id in the data.


```{r}
instacart|>
  count(aisle,name="n_items")|>
  arrange(desc(n_items))

```
>> There are 134 aisle in the instacart dataset. The most items order aisle is fresh vegetable.

```{r}
instacart|>
  count(aisle,name="n_items")|>
  filter(n_items>10000)|>
  mutate(aisle=fct_reorder(aisle,n_items))|>
  ggplot(aes(x=aisle,y=n_items))+
  geom_point()+
  theme(axis.text.x = element_text(angle = 65, vjust = 1, hjust=1))+
  ggtitle("Number of Items in Each Aisle")
  
```

```{r}
top3_product=instacart|>
  filter(aisle==c("baking ingredients", "dog food care", "packaged vegetables fruits"))|>
  group_by(aisle)|>
  count(product_name)|>
  mutate(rank = min_rank(desc(n))) |>
  filter(rank < 4) |>
  arrange(desc(n))|>
  select(-rank)

top3_product
```


```{r}
coffee_apple=instacart|>
  filter(product_name==c("Pink Lady Apples", "Coffee Ice Cream"))|>
  mutate(order_dow=factor(order_dow, labels = c("Monday","Tueday","Wednesday","Thursday","Friday", "Saturday", "Sunday")))|>
  group_by(product_name,order_dow)|>
  summarize(mean_time=mean(order_hour_of_day))|>
  pivot_wider(names_from = order_dow,
              values_from = mean_time)
coffee_apple
  
```
## Problem 2

```{r}
brfss_smart_df=brfss_smart2010|>
  janitor::clean_names()|>
  rename(states_abbrev=locationabbr,
         states_county=locationdesc,
         responde_id=respid)|>
  

```

